### ISSUE TITLE
Fix version returned by `polykey --version`

### ISSUE THREAD

**Issue by tegefaulkes** [MatrixAI/Polykey-CLI#172]
### Specification

Right not the Polykey version returned by the `commander` built in `--version` flag. This is returning the library version number and not the CLI version number.

```
❯ npm run polykey -- --version

> polykey-cli@0.3.0 polykey
> ts-node src/polykey.ts --version

1.2.2-alpha.2
```

This *should* return either the `CLI` version of `0.3.0` or the full length version formatted like `0.3.0|1.2.3|alpha.3|1|1` where it's structured as `APPVERSION|LIBRARYVERSION|NETWORKVERSION|STATEVERSION`

These should be the versions used by the CLI directly and not what is returned via the `agent status` over the RPC. The client and server versions are different.

This can be set using the `commander` `program.version('0.0.1');` method to set this. The version number itself needs to be constructed from the relevant config and `package.json` information.

### Tasks

- [X] 1\. Create a utility that constructs the version numbers from the relevant information from config and `package.json` files.
- [X] 2\. Set the version on commander using `program.version` method.
- [ ] 3\. Add a test checking for regressions.

**Comment by tegefaulkes** [comment]
There's an alternative formatting we can do here. Frankly any string is valid as far as `commander` is concerned.

```
❯ npm run polykey -- --version

> polykey-cli@0.4.1 polykey
> ts-node src/polykey.ts --version

{
 "appVersion": "0.4.1",
 "libraryVersion": "1.5.1",
 "networkVersion": "1",
 "stateVersion": "1"
}
```

**Comment by tegefaulkes** [comment]
I've pretty much completed this and ready to push. The change is very simple so I'm going skip a PR for this one. I just need some feedback for the alternative formatting above. I think it's more clear what each version number is for.<br><br>I could also modify the version description.

```
> ts-node src/polykey.ts --help

Usage: polykey [options] [command]

Polykey CLI

Options:
  -np, --node-path <path>      Path to Node State (default: "/home/brian/.local/share/polykey", env: PK_NODE_PATH)
  -pf, --password-file <path>  Path to Password
  -f, --format <format>        Output Format (choices: "human", "json", default: "human")
  -v, --verbose                Log Verbose Messages (default: 0)
  -V, --version                <Your description here!>
  -V, --version                output the version number
  -h, --help                   display help for command
```

**Comment by CMCDragonkai** [comment]
I think you should should keep the version output to one line!

Do not format it into a multiline object. Version outputs are often checked.

Yes a single line json could be used...

In fact an array could be used to reduce verbosity and that array order could be in the order we designate. The help description we can say too.

**Comment by tegefaulkes** [comment]
Alright, I'll format it as an array and update the description.
