### ISSUE TITLE
Create tests for PolykeyAgent stability during random agent-agent interactions

### ISSUE THREAD

**Issue by tegefaulkes** [MatrixAI/Polykey-CLI#8]
### Specification

It's possible that during an agent-agent communication we don't properly catch all possible errors. Failing to catch these errors can result if the `PolykeyAgent` crashing randomly. We need to create a test to check for these conditions so we can prevent any problems. 

1. There should never be a condition where the failure of an agent causes an connected agent to crash.
2. There should never be a condition where general operation of a `PolykeyAgent` causes it to crash.

We need to create tests where we do random agent-agent interactions and then force the crash of either the client or agent node. We need to make sure either of these agents don't crash unexpectedly. given the randomness of the test and how expensive starting agents are, it's unlikely to catch these errors very often but just having these tests covers our bases. These tests should be using `fast-check` to allow randomness of the testing.

### Additional context

- Related MatrixAI/Polykey#445 

### Tasks

- [ ] 1. Create a test where we have random interaction between agent 1 and agent 2 where agent 2 crashes at a random time.
- [ ] 2. Create a test where we have random interaction between agent 1 and agent 2 where agent 1 crashes at a random time.
- [ ] 3. Create a test where an agent runs for a period of time preforming random tasks without crashing.

**Comment by CMCDragonkai** [comment]
This is now moved into PK CLI.

However agent to agent interactions can be done in the CI, more complex simulations needs to be done as part of the testnet which is already deployed. We just need to apply some chaos monkey to our orchestrator in testnets. We can imagine a more sophisticated QA process in the future.
